services:
  flutter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8089:8080
    networks:
      - snapshotter
    depends_on:
      - xvfb
  xvfb:
    expose:
      - 6069
    build:
      context: .
      dockerfile: Dockerfile.xvfb
    networks:
      - snapshotter
networks:
  snapshotter:
